<html>
<head>
	<link href="estilos.css" rel="stylesheet" type="text/css" />
</head>

<body id='cuerpo_legal'>

<div id='nota_legal'>
<!--<img src='images_css/logo.png'><br><br>-->
<span class='titulo'>INFORMACI&Oacute;N LEGAL.</span><br> 	 
<hr>
<br>
<span class='titulo'>Titularidad del portal</span><br><br>
	 
<b>Denominaci&oacute;n Social:</b><br>
	El Pollo Andaluz S.C.<br><br>

<b>CIF:</b><br>
	<br><br>

<b>Domicilio Social:</b><br>
	C/ Fray Diego de Cadiz 2,<br>
Moron de la frontera (Sevilla)<br><br>
<hr>
<br>
<span class='titulo'>Aviso Legal</span><br><br>

 	 
Con car&aacute;cter general, las relaciones entre El pollo andaluz S.C. y sus clientes derivadas de la visita a los contenidos de la presente web o de la adquisici&oacute;n de los productos ofertados en la misma, se encuentran sometidas a la legislaci&oacute;n y jurisdicci&oacute;n espa&ntilde;olas. Este Website tiene car&aacute;cter informativo, promocional y es para uso estrictamente personal. El hecho de acceder a este website implica el conocimiento y aceptaci&oacute;n de los siguientes t&eacute;rminos y condiciones.<br><br>

La vista a esta webhome no supone que el usuario est&eacute; obligado a facilitar ninguna informaci&oacute;n sobre si mismo. En caso de que el usuario voluntariamente proporcione alguna informaci&oacute;n de car&aacute;cter personal, los datos recogidos se utilizar&aacute;n y tratar&aacute;n con la finalidad de gestionar la entrega de su pedido a domicilio, en su caso, as&iacute; como informarle sobre futuras acciones promocionales y publicitarias de nuestra empresa mediante cualquier medio, incluyendo el env&iacute;o de correos electr&oacute;nicos y de mensajes a trav&eacute;s de cualquier sistema incluyendo SMS, UTMS, etc., que puedan ser de su inter&eacute;s para ampliar y mejorar la calidad de los productos y servicios de la Cadena El pollo andaluz, as&iacute; como adecuar nuestras ofertas a sus preferencias o necesidades, a partir del estudio y segmentaci&oacute;n de la informaci&oacute;n personal y comercial que conste en nuestros ficheros como consecuencia de su acceso a nuestra webhome, incluso mediante encuestas especialmente dirigidas, trat&aacute;ndose no obstante los mismos en cualquier caso en la forma y con las limitaciones y derechos que recoge la Ley Org&aacute;nica 15/1999 de Protecci&oacute;n de Datos de Car&aacute;cter Personal dentro del marco establecido por la legislaci&oacute;n espa&ntilde;ola.<br><br>

Los datos facilitados por los usuarios ser&aacute;n incorporados a los ficheros de car&aacute;cter personal de los que es responsable El pollo andaluz S.C., garantiza el cumplimiento de la normativa de Protecci&oacute;n de Datos de Car&aacute;cter Personal, y as&iacute;, de acuerdo con la L.O. 15/1999, el cliente o usuario queda informado y presta su consentimiento a la incorporaci&oacute;n de sus datos a los ficheros informatizados propiedad de El pollo andaluz S.C., y al tratamiento automatizado de los mismos con las finalidades anteriormente mencionadas.<br><br>

El Cliente o usuario acepta que puedan ser cedidos sus datos, exclusivamente para las finalidades a las que se refiere el p&aacute;rrafo primero, a otras empresas del Grupo y/o Cadena El pollo andaluz dentro del sector de la restauraci&oacute;n, as&iacute; como a otras empresas afines a nuestras actividades y promociones (ocio, viajes, alimentaci&oacute;n, telecomunicaciones, cultura y servicios) que colaboren ahora o en el futuro en las actividades o campa&ntilde;as promocionales que desarrolle El pollo andaluz S.C., aceptando por tanto expresamente el cliente o usuario que El pollo andaluz S.C. o las referidas sociedades, les remitan informaci&oacute;n sobre los productos que comercialicen. La aceptaci&oacute;n del cliente o usuario para que puedan ser tratados o cedidos sus datos en la forma establecida en este p&aacute;rrafo, tiene siempre car&aacute;cter revocable, sin efectos retroactivos, conforme a lo que disponen los art&iacute;culos 6 y 11 de la Ley Org&aacute;nica 15/1999 de 13 de Diciembre.<br><br>

De conformidad con lo establecido en la Ley Org&aacute;nica 15/1999 del 14 de Diciembre de Protecci&oacute;n de Datos de Car&aacute;cter Personal el cliente o usuario queda igualmente informado sobre la posibilidad de ejercer los derechos de acceso, rectificaci&oacute;n, cancelaci&oacute;n y oposici&oacute;n, en los t&eacute;rminos establecidos en la legislaci&oacute;n vigente, siendo PEl pollo andaluz S.C. el responsable del fichero automatizado y pudiendo dirigirse por escrito al Departamento de Marketing de El pollo andaluz, C/ Fray Diego de Cadiz 2, Moron de la frontera (Sevilla) o bien mediante correo electr&oacute;nico a la siguiente direcci&oacute;n; info@pizza-house.es<br><br>

El acceso a los servicios, productos, contenidos o el registro en cualquiera de los formularios de solicitud de datos personales existentes en nuestra webhome se realizar&aacute; bajo la m&aacute;s completa responsabilidad de los Usuarios. En caso de que se trate de menores de edad o incapaces, se realizar&aacute; a la entera responsabilidad de sus padres, representantes o tutores legales, debiendo &eacute;stos en todo caso, acompa&ntilde;ar, supervisar o tomar las precauciones oportunas durante la navegaci&oacute;n de aquellos por las paginas web.<br><br>

Igualmente se informa por parte de El pollo andaluz S.C. de la imposibilidad de realizar comprobaciones sobre la veracidad y exactitud de los datos personales proporcionados, por lo que recomienda para los casos de tales actuaciones que supervisen el proceso de registro de sus hijos o tutelados. En su caso, El pollo andaluz S.C., gestionar&aacute; las solicitudes derivadas del ejercicio, por los padres o tutores, de los derechos de acceso, cancelaci&oacute;n, rectificaci&oacute;n y oposici&oacute;n de los datos de los menores o incapaces, sin perjuicio de que puede ponerse en contacto con nosotros para realizar las advertencias que considere oportunas, por cualquiera de los medios ya referenciados.<br><br>

En el momento de proceder a la recogida de los datos se indicar&aacute; el car&aacute;cter voluntario u obligatorio de los datos objeto de recogida. La negativa a proporcionar los datos calificados obligatorios supondr&aacute; la no prestaci&oacute;n o la imposibilidad de acceder al servicio para los que eran solicitados.<br><br>


<b>Pol&iacute;tica de Privacidad.</b><br><br>

Los contenidos, promociones, pedidos, etc., incluidos en este website no est&aacute;n concebidos ni dirigidos a aquellas personas f&iacute;sicas o jur&iacute;dicas que residan en jurisdicciones donde sus contenidos no se encuentren autorizados. El acceso a este website es responsabilidad exclusiva de los usuarios. El acceso a este website no supone entablar ning&uacute;n tipo de relaci&oacute;n de car&aacute;cter comercial entre El pollo andaluz S.C. y el usuario. El acceso y navegaci&oacute;n en este website supone aceptar y conocer las advertencias legales, condiciones y t&eacute;rminos de uso contenidas en ella.<br><br>

El usuario reconoce y acepta que la utilizaci&oacute;n de la web as&iacute; como la adquisici&oacute;n de los productos ofrecidos se realiza bajo su entero riesgo y su entera responsabilidad. El pollo andaluz S.C., no se hace responsable de los perjuicios que se pudieran derivar por ello. El pollo andaluz S.C., no controla con car&aacute;cter general, la utilizaci&oacute;n que los usuarios hacen de la Web. Los usuarios se comprometen a actuar de conformidad con la Ley, las presentes Condiciones, la moral y las buenas costumbres generalmente aceptadas y el orden p&uacute;blico, de forma diligente y prudente. Igualmente y en caso de que se trate de menores de edad o incapaces, se realizar&aacute; a la entera responsabilidad de sus padres, representantes o tutores legales, debiendo &eacute;stos acompa&ntilde;ar, supervisar o tomar las precauciones oportunas durante la navegaci&oacute;n de aquellos por las paginas web.<br><br>

Por tanto y sin perjuicio de todo lo previsto como Aviso Legal; en su condici&oacute;n de padres, representantes o tutores legales, ser&aacute;n los responsables de que sus hijos menores o tutelados accedan a los servicios, productos o contenidos de El pollo andaluz S.C. o se registren, por lo que les recomendamos acompa&ntilde;ar, supervisar o tomar las precauciones oportunas (reglas de tiempo de uso de ordenador, ubicaci&oacute;n del ordenador en zona com&uacute;n de la casa, etc.) durante la navegaci&oacute;n de aquellos por las p&aacute;ginas web.<br><br>

Junto a lo anterior, le recordamos que algunos navegadores permiten modificar su configuraci&oacute;n para que los ni&ntilde;os u otras personas no puedan acceder a determinadas p&aacute;ginas. A&uacute;n as&iacute; le recomendamos que asista a la navegaci&oacute;n pues determinados websites podr&iacute;an no haber sido clasificados.<br><br>

Las presentes Condiciones, junto con las Condiciones Generales de Contrataci&oacute;n y/o las Condiciones Particulares que puedan establecerse, tienen por finalidad regular la puesta a disposici&oacute;n de la informaci&oacute;n as&iacute; como las relaciones comerciales que surjan entre El pollo andaluz S.C., y los Usuarios.<br><br>

La informaci&oacute;n que aparece en este website es la vigente en la fecha de su &uacute;ltima actualizaci&oacute;n. El pollo andaluz S.C. se reserva el derecho a actualizar, modificar o eliminar la informaci&oacute;n de este website, pudiendo limitar o no permitir el acceso a este website. El pollo andaluz realiza los m&aacute;ximos esfuerzos para evitar cualquier error en los contenidos que pudieran aparecer en este website. El pollo andaluz S.C. no garantiza, ni se responsabiliza de las consecuencias que pudieran derivarse de los errores en los contenidos que pudieran aparecer en este website, proporcionados por terceros. El pollo andaluz S.C. se reserva la facultad de efectuar, en cualquier momento, cuantos cambios y modificaciones estime convenientes, pudiendo hacer uso de tal facultad en cualquier momento y sin previo aviso. El pollo andaluz S.C. no asume responsabilidad alguna por las discrepancias que pudiesen existir entre los documentos impresos y la versi&oacute;n electr&oacute;nica publicada en este website. En caso de discrepancia entre la versi&oacute;n impresa y la publicada en el website, prevalecer&aacute; la versi&oacute;n impresa.<br><br>


Los contenidos que se muestran en la web, dise&ntilde;os, textos, gr&aacute;ficos, logos, iconos, software, nombres comerciales, marcas, dibujos industriales o cualesquiera otros signos susceptibles de utilizaci&oacute;n industrial y comercial est&aacute;n sujetos a derechos de propiedad intelectual e industrial de El pollo andaluz S.C., o de terceros titulares de los mismos que han autorizado expresa y debidamente su inclusi&oacute;n.. En ning&uacute;n caso de entender&aacute; que se concede licencia alguna o se efect&uacute;a renuncia, transmisi&oacute;n, cesi&oacute;n total o parcial de dichos derechos ni se confiere ning&uacute;n derecho ni expectativa de derecho y en especial de alteraci&oacute;n, explotaci&oacute;n, reproducci&oacute;n, distribuci&oacute;n o comunicaci&oacute;n publica sobre dichos contenidos sin la previa autorizaci&oacute;n expresa de El pollo andaluz S.C. o de los titulares correspondientes. No se podr&aacute; establecer ning&uacute;n vinculo desde cualquier otra Web sin el previo y expreso consentimiento de El pollo andaluz S.C..<br><br>


El pollo andaluz S.C. excluye toda responsabilidad que pudiera derivarse de la transmisi&oacute;n de informaci&oacute;n entre usuarios. La responsabilidad de las manifestaciones difundidas en este website es exclusiva de quienes las realizan. Queda prohibida cualquier tipo de transmisi&oacute;n de datos que los usuarios puedan realizar a &eacute;ste o mediante este website u otros accesos controlados por El pollo andaluz S.C., que infrinjan los derechos de propiedad de terceros, y cuyo contenido sea amenazante, difamatorio, pornogr&aacute;fico, etc.., o la transmisi&oacute;n de cualquier otro material que constituya o incite una conducta tipificada penalmente. El pollo andaluz S.C. se reserva el derecho a impedir o prohibir el acceso a cualquier usuario de Internet que introduzca en este website cualquier contenido contrario a las normas legales o inmoral, reserv&aacute;ndose el derecho de ejercer las medidas legales que estime oportunas para evitar este tipo de conductas.<br><br>

La existencia de links en el website de El pollo andaluz S.C., salvo manifestaci&oacute;n expresa en contrario, tiene una finalidad meramente informativa y en ning&uacute;n caso supone sugerencia, invitaci&oacute;n o recomendaci&oacute;n sobre los mismos. Estos enlaces no representan ning&uacute;n tipo de relaci&oacute;n entre El pollo andaluz S.C. y los particulares o empresas titulares de los websites a los que puede accederse mediante estos enlaces. No se podr&aacute; alterar, cambiar, modificar, o adaptar este website. El pollo andaluz S.C.. se reserva el derecho de retirar de modo unilateral y en cualquier momento los links que aparecen en su website. El pollo andaluz S.C. no asume responsabilidad por el contenido de cualquier foro o debate (chat), o cualquier tipo de transmisiones, que est&eacute;n vinculadas a este website y cooperar&aacute;, si es requerida por orden judicial o por las autoridades pertinentes, en la identificaci&oacute;n de las personas responsables de aquellos contenidos que violen la ley.<br><br>

El acceso y navegaci&oacute;n en este website supone aceptar y conocer las advertencias legales, condiciones y t&eacute;rminos de uso contenidas en ella. El pollo andaluz S.C. realiza los m&aacute;ximos esfuerzos para que la navegaci&oacute;n se realice en las mejores condiciones y evitar los perjuicios de cualquier tipo que pudiesen ocasionarse durante la misma. El pollo andaluz S.C. no se responsabiliza en modo alguno de aquellos contenidos que pudiesen visualizarse mediante enlaces electr&oacute;nicos (links), directa o indirectamente, a trav&eacute;s de este website<br><br>

Este website ha sido dise&ntilde;ado para soportar los navegadores Mozilla Fierfox 3.6 y Internet Explorer 5.00 o superior y El pollo andaluz S.C. no se hace responsable de los perjuicios, de cualquier &iacute;ndole, que pudieran ocasionarse a los usuarios por la utilizaci&oacute;n de otros navegadores o versiones distintas de los navegadores para los que ha sido dise&ntilde;ado el website. El pollo andaluz S.C. no se responsabiliza ni garantiza que el acceso a este website sea ininterrumpido o que est&eacute; libre de error. Tampoco se responsabiliza o garantiza que el contenido o software al que pueda accederse a trav&eacute;s de este website, est&eacute; libre de error o cause un da&ntilde;o. En ning&uacute;n caso El pollo andaluz S.C. ser&aacute; responsable por las p&eacute;rdidas, da&ntilde;os o perjuicios de cualquier tipo que surjan por el acceso y el uso de la p&aacute;gina web, incluy&eacute;ndose pero no limit&aacute;ndose, a los ocasionados a los sistemas inform&aacute;ticos o los provocados por la introducci&oacute;n de virus. El pollo andaluz S.C. no se hace responsable de los da&ntilde;os que pudiesen ocasionarse a los usuarios por un uso inadecuado de este website.<br><br>

Los servicios ofertados en este website s&oacute;lo pueden ser utilizados correctamente si se cumplen las especificaciones t&eacute;cnicas para las que ha sido dise&ntilde;ado. El pollo andaluz S.C. no ser&aacute; responsable de posibles da&ntilde;os o perjuicios que se pudieran derivar de interferencias omisiones, interrupciones, virus inform&aacute;ticos, aver&iacute;as telef&oacute;nicas o desconexiones en el funcionamiento operativo de este sistema electr&oacute;nico, motivadas por causas ajenas a El pollo andaluz S.C. de retrasos o bloqueos en el uso del presente sistema electr&oacute;nico causados por deficiencias o sobrecargas en su Centro de Procesos de Datos, de l&iacute;neas telef&oacute;nicas , en el sistema de Internet o en otros sistemas electr&oacute;nicos; ni tampoco de da&ntilde;os que puedan ser causados por terceras personas mediante intromisiones ileg&iacute;timas fuera del control de El pollo andaluz S.C.. Asimismo, se exonera a El pollo andaluz S.C. de responsabilidad ante cualquier da&ntilde;o o perjuicio que pudiera sufrir el usuario como consecuencia de errores, defectos u omisiones, en la informaci&oacute;n facilitada por El pollo andaluz S.C. siempre que proceda de fuentes ajenas.<br><br>

Las partes renuncian expresamente al fuero que les pudiera corresponder y se someten expresamente a los Juzgados y Tribunales de Sevilla para resolver cualquier controversia que pueda surgir en la interpretaci&oacute;n o ejecuci&oacute;n de las presentes condiciones contractuales.<br><br>


<b>Protecci&oacute;n de datos de car&aacute;cter personal.</b><br><br>

De acuerdo con lo establecido en la Ley Org&aacute;nica 15/1999, el usuario queda informado de la incorporaci&oacute;n de sus datos personales a un fichero automatizado propiedad de El pollo andaluz S.C., as&iacute; como del tratamiento automatizado a que van a ser sometidos los datos personales que nos proporciona al rellenar el formulario adjunto, as&iacute; como cualquier otro dato adicional al que El pollo andaluz S.C. pueda tener acceso como consecuencia de la consulta realizada a nuestra webhome, registro en la misma o adquisici&oacute;n a trav&eacute;s de ella de cualquiera de nuestros productos. La finalidad de dicho fichero es gestionar la entrega de su pedido a domicilio, en su caso, as&iacute; como informarle sobre futuras acciones promocionales y publicitarias de nuestra empresa mediante cualquier medio, incluyendo el env&iacute;o de correos electr&oacute;nicos y de mensajes a trav&eacute;s de cualquier sistema incluyendo SMS, UTMS, etc., que puedan ser de su inter&eacute;s para ampliar y mejorar la calidad de los productos y servicios de la Cadena El pollo andaluz, as&iacute; como adecuar nuestras ofertas a sus preferencias o necesidades, a partir del estudio y segmentaci&oacute;n de la informaci&oacute;n personal y comercial que conste en nuestros ficheros como consecuencia de su acceso a nuestra webhome, incluso mediante encuestas especialmente dirigidas.<br><br>

El cliente o usuario tiene derecho a oponerse al tratamiento de cualquiera de sus datos que no sean imprescindibles y por tanto obligatorios para la entrega del pedido a domicilio, siendo facultativas por tanto las respuestas que pudiere dar a las cuestiones que se le planteen al margen del nombre, direcci&oacute;n y tel&eacute;fono. El cliente o usuario acepta que sus datos puedan ser cedidos exclusivamente para las finalidades a las que se refiere esta cl&aacute;usula, a cualquiera de las empresas integrantes del Grupo y/o Cadena El pollo andaluz dentro del sector de la restauraci&oacute;n, as&iacute; como a otras empresas afines a nuestras actividades y promociones (ocio, viajes, alimentaci&oacute;n, telecomunicaciones, cultura y servicios) que colaboren ahora o en el futuro en las actividades o campa&ntilde;as promocionales que desarrolle El pollo andaluz S.C.. La aceptaci&oacute;n del cliente o usuario para que puedan ser tratados o cedidos sus datos en la forma establecida en este p&aacute;rrafo tiene siempre car&aacute;cter revocable, sin efectos retroactivos, conforme a lo que disponen los art&iacute;culos 6 y 11 de la Ley Org&aacute;nica 15/1999 de 13 de Diciembre.<br><br>

El cliente o usuario queda igualmente informado sobre la posibilidad de ejercer los derechos de acceso, rectificaci&oacute;n, cancelaci&oacute;n y oposici&oacute;n, en los t&eacute;rminos establecidos en la legislaci&oacute;n vigente, siendo El pollo andaluz S.C. el responsable del fichero automatizado y pudiendo dirigirse por escrito al Departamento de Marketing de El pollo andaluz S.C., calle Fray Diego de Cadiz, 2. Moron de la frontera (Sevilla) o bien mediante correo electr&oacute;nico a la siguiente direcci&oacute;n; manolo@elpolloandaluz.es<br><br>

El registro en cualquiera de los formularios de solicitud de datos personales existentes en nuestra webhome se realizar&aacute; bajo la m&aacute;s completa responsabilidad de los Usuarios. En caso de que se trate de menores de edad o incapaces, se realizar&aacute; a la entera responsabilidad de sus padres, representantes o tutores legales, debiendo &eacute;stos en todo caso, acompa&ntilde;ar, supervisar o tomar las precauciones oportunas durante la navegaci&oacute;n de aquellos por las paginas web. No obstante, El pollo andaluz S.C., gestionar&aacute; las solicitudes derivadas del ejercicio, por los padres o tutores, de los derechos de acceso, cancelaci&oacute;n, rectificaci&oacute;n y oposici&oacute;n de los datos de los menores o incapaces, por cualquiera de los medios ya referenciados, sin perjuicio de que puede ponerse en contacto con nosotros para realizar las advertencias que considere oportunas.<br><br>
</div>
</body>
</html>